import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by betich's boilerplate Next.js template" />
      </Head>
      <main>Next.js boilerplate template</main>
    </>
  );
};

export default Home;
